# Prerequisites

In [55]:
%pip install -r requirements.txt

Requirement already satisfied: altair==6.0.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (6.0.0)
Requirement already satisfied: attrs==26.1.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (26.1.0)
Requirement already satisfied: blinker==1.9.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (1.9.0)
Requirement already satisfied: cachetools==7.0.5 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (7.0.5)
Requirement already satisfied: certifi==2026.2.25 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 5)) (2026.2.25)
Requirement already satisfied: charset-normalizer==3.4.7 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 6)) (3.4.7)
Requirement already satisfied: click==8.3.2 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 7)) (8.3.2)
Requirement already satisfied: colorama==0.4.6 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 8)) (0.4.6)
Requirement already satisfied: gitdb==4.0.12 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 9)) (4.0.12)
Requirement already satisfied: GitPython==3.1.46 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 10)) (3.1.46)
Requirement already satisfied: idna==3.11 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 11)) (3.11)
Requirement already satisfied: Jinja2==3.1.6 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 12)) (3.1.6)
Requirement already satisfied: joblib==1.5.3 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 13)) (1.5.3)
Requirement already satisfied: jsonschema==4.26.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 14)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 15)) (2025.9.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 16)) (3.0.3)
Requirement already satisfied: narwhals==2.19.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 17)) (2.19.0)
Requirement already satisfied: nltk==3.9.4 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 18)) (3.9.4)
Requirement already satisfied: numpy==2.4.4 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 19)) (2.4.4)
Requirement already satisfied: packaging==26.1 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 20)) (26.1)
Requirement already satisfied: pandas==3.0.2 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 21)) (3.0.2)
Requirement already satisfied: pillow==12.2.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 22)) (12.2.0)
Requirement already satisfied: protobuf==7.34.1 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 23)) (7.34.1)
Requirement already satisfied: pyarrow==23.0.1 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 24)) (23.0.1)
Requirement already satisfied: pydeck==0.9.2 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 25)) (0.9.2)
Requirement already satisfied: python-dateutil==2.9.0.post0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 26)) (2.9.0.post0)
Requirement already satisfied: referencing==0.37.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 27)) (0.37.0)
Requirement already satisfied: regex==2026.4.4 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 28)) (2026.4.4)
Requirement already satisfied: requests==2.33.1 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 29)) (2.33.1)
Requirement already satisfied: rpds-py==0.30.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 30)) (0.30.0)
Requirement already satisfied: scikit-learn==1.8.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 31)) (1.8.0)
Requirement already satisfied: scipy==1.17.1 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 32)) (1.17.1)
Requirement already satisfied: six==1.17.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 33)) (1.17.0)
Requirement already satisfied: smmap==5.0.3 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 34)) (5.0.3)
Requirement already satisfied: streamlit==1.56.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 35)) (1.56.0)
Requirement already satisfied: tenacity==9.1.4 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 36)) (9.1.4)
Requirement already satisfied: threadpoolctl==3.6.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 37)) (3.6.0)
Requirement already satisfied: toml==0.10.2 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 38)) (0.10.2)
Requirement already satisfied: tornado==6.5.5 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 39)) (6.5.5)
Requirement already satisfied: tqdm==4.67.3 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 40)) (4.67.3)
Requirement already satisfied: typing_extensions==4.15.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 41)) (4.15.0)
Requirement already satisfied: tzdata==2026.1 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 42)) (2026.1)
Requirement already satisfied: urllib3==2.6.3 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 43)) (2.6.3)
Requirement already satisfied: watchdog==6.0.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 44)) (6.0.0)
Note: you may need to restart the kernel to use updated packages.

In [56]:
# Auto-reload module eksternal setiap cell dijalankan ulang
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Load file artikel

In [57]:
from pathlib import Path
import pandas as pd

article_path = Path("article.md")
article = article_path.read_text(encoding="utf-8")

print(f"Loaded: {article_path} ({len(article)} karakter)")
print(article)  # preview

Loaded: article.md (7250 karakter)
# What is Anthropic's Claude Mythos and what risks does it pose?

16 hours ago

Liv McMahon,Technology reporterand

Joe Tidy,Cyber correspondent, BBC World Service

![](https://static.files.bbci.co.uk/bbcdotcom/web/20260407-092955-f3cfe0ee04-web-3.0.0-2/grey-placeholder.png)!Reuters A smartphone display showing the Anthropic logo in black letters on an all-white background, laid on a laptop keyboard lit in pink and purpleReuters

In recent weeks, the AI world has been a-buzz following claims made by leading firm, Anthropic, regarding its new model, Claude Mythos.

The company says it found the tool can outperform humans at some hacking and cyber-security tasks, which has prompted discussions by regulators, legislators and financial institutions about the dangers it could pose to digital services.

Several tech giants have been given access to Mythos via an initiative called Project Glasswing, designed to strengthen resilience to Mythos itself.

But others point out that it is in Anthropic's interests to suggest its tool has never-seen-before capabilities, meaning - as ever with AI - the job of distinguishing between justified claims and hype can be tricky.

## What is Claude Mythos?

Mythos is one of Anthropic's latest models developed as part of its broader AI system called Claude. It encompasses the company's AI assistant and family of models, rivalling OpenAI's ChatGPT and Google's Gemini.

It was revealed by Anthropic in early April as "Mythos Preview".

Researchers who test how AI models handle particular requests or tasks, known as "red-teams", said in a report Mythos was "strikingly capable at computer security tasks".

They found the tool could locate dormant bugs lurking in decades-old code and easily exploit them.

So rather than make it widely available to Claude users, Anthropic gave 12 tech companies access via Project Glasswing, which it described as "an effort to secure the world's most critical software".

They include cloud computing giant Amazon Web Services, device manufacturers Apple, Microsoft and Google, and chip-makers Nvidia and Broadcom.

Crowdstrike, whose faulty software update caused a major global outage in July 2024, is also among the project's partners, with Anthropic saying it has also given access to Mythos to more than 40 organisations responsible for critical software.

In a video released alongside Project Glasswing's launch, Anthropic boss Dario Amodei said it had offered to work with US government officials to "help defend against the risk of these models".

## Why are there concerns?

Anthropic says during tests it found the model was highly skilled at cyber-security and hacking tasks, outperforming humans.

"Mythos Preview has already found thousands of high-severity vulnerabilities, including some in every major operating system and web browser," Anthropic claimed on 7 April.

"Given the rate of AI progress, it will not be long before such capabilities proliferate, potentially beyond actors who are committed to deploying them safely."

It said it could locate - without much oversight - critical bugs in need of immediate action in old systems, including one vulnerability which had been present in a system for 27 years, and suggest ways to exploit them.

![](https://static.files.bbci.co.uk/bbcdotcom/web/20260407-092955-f3cfe0ee04-web-3.0.0-2/grey-placeholder.png)!Reuters People march through San Francisco, USA, carrying placards against AI. They are smiling on a sunny day and one man wears a high visibility vest.Reuters

Public fears over the capabilities of AI led to a protest in San Francisco in March

Canadian finance minister François-Philippe Champagne told the BBC Mythos had been discussed at a International Monetary Fund (IMF) meeting in Washington DC this week.

"Certainly it is serious enough to warrant the attention of all the finance ministers," he said, describing the tech as an "unknown unknown".

Bank of England boss Andrew Bailey told the BBC "we are having to look very carefully now what this latest AI development could mean for the risk of cyber crime."

Meanwhile, the EU has said it is also in discussions with Anthropic about its concerns around Mythos.

- Listen: The AI model that’s ‘too powerful’ to be released to the public

## What have cyber experts said about it?

Ciaran Martin, former head of the UK's National Cyber Security Centre, told the BBC earlier this week the claim Mythos could unearth critical vulnerabilities much more quickly than other AI models had "really shaken people".

"The second thing is that even with existing weaknesses that we know about, but organisations might not have patched against, might not be well defended against, it's just a really good hacker," he said.

Many independent cyber-security analysts and experts have not yet been able to test it themselves and some remain sceptical about Mythos' performance.

The UK's AI Safety Institute recently concluded that while a very powerful model, its biggest threat would be against poorly defended, vulnerable systems.

"We cannot say for sure whether Mythos Preview would be able to attack well-defended systems," its researchers said.

So where there is good cybersecurity, this model would, in theory, hopefully be stopped.

## Should we be worried about it?

Fears relating to AI are nothing new.

New models and tools are coming out all the time, and are often accompanied by promises to revolutionise our lives, for better or worse.

Capitalising on this mix of fear and excitement over AI and its future impact has also become a hallmark of the sector and its marketing strategies in recent years.

In the case of Mythos, we still do not know enough about to know whether these hopes or fears are justified, or more a reflection of the hype surrounding the industry.

![](https://static.files.bbci.co.uk/bbcdotcom/web/20260407-092955-f3cfe0ee04-web-3.0.0-2/grey-placeholder.png)!Reuters CEO of Anthropic Dario Amodei, addresses the gathering at the AI Impact Summit, in New Delhi, India. He wears glasses, a dark suit and a purple tie, sitting against a purple background. There is a microphone in his hand as he addresses somebody unseen.Reuters

Anthropic CEO Dario Amodei has warned against misuse of the company's products before

In either cases, according to the NSCS, the most important thing we can do now is not panic and instead focus on the need to get the basic cyber-security right.

After all, most hackers do not need super AI tools to breach systems when much simpler attacks often suffice.

"For some this is an apocalyptic event, for others it seems to be a lot of hype," Martin told the BBC.

But he said whether it was this tool or subsequent ones made by Anthropic or its rivals, alongside the risk there was an opportunity to build a safer online world.

"In the medium-term, there's an opportunity to use these tools to fix a lot of the underlying vulnerabilities in the internet," he said.

![](https://static.files.bbci.co.uk/bbcdotcom/web/20260407-092955-f3cfe0ee04-web-3.0.0-2/grey-placeholder.png)!A green promotional banner with black squares and rectangles forming pixels, moving in from the right. The text says: “Tech Decoded: The world’s biggest tech news in your inbox every Monday.”

# Proses

## Pecah menjadi beberapa paragraph

In [58]:
import importlib
import preprocess

# Pastikan module eksternal memakai versi terbaru dari file .py
importlib.reload(preprocess)

# ambil query dari heading pertama markdown
first_nonempty_line = next((line.strip() for line in article.splitlines() if line.strip()), "")
# print(f"First non-empty line: {first_nonempty_line}")
query = first_nonempty_line.lstrip("#").strip()
print(f"Query: {query}")
query_tokens = preprocess.preProcess(query)
print(f"Query Tokens: {query_tokens}\n")

paragraphs = preprocess.splitParagraph(article)
print(f"Split into {len(paragraphs)} paragraphs")

Query: What is Anthropic's Claude Mythos and what risks does it pose?
Query Tokens: ['anthrop', 'claud', 'mytho', 'risk', 'pose']

Split into 5 paragraphs

[nltk_data] Downloading package punkt to /home/juana/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

## Proses setiap Paragraph

In [ ]:
import preprocess
import counter

# ===============================
# STORAGE
# ===============================
tf_global = {}          # TF semua dokumen
tf_paragraph = {}       # TF per paragraph
df_all = {}             # DF per paragraph
idf_paragraph = {}      # IDF per paragraph
tfidf_paragraph = {}    # TF-IDF per paragraph


doc_counter = 1

# ===============================
# MAIN LOOP
# ===============================
for i, (title, content) in enumerate(paragraphs.items(), start=1):
    
    paragraph_key = f"P{i}"
    print(f"Processing {paragraph_key}/{len(paragraphs)} : {title}")
    
    docs = preprocess.splitDocument(content)
    print(f"  Split into {len(docs)} documents")
    # -------------------------------
    # PREPROCESS ALL DOCS
    # -------------------------------
    clean_docs = []
    paragraph_tf = {}


    
    # hitung tf dan idf query
    doc_key = "QUERY"
    tf_entry = {
        term: counter.tf_counter(term, query_tokens)
        for term in query_tokens
    }
    tf_global[doc_key] = tf_entry
    paragraph_tf[doc_key] = tf_entry
        
        
    for doc in docs:
        clean_doc = preprocess.preProcess(doc)
        clean_docs.append(clean_doc)

        doc_key = f"D{doc_counter}"

        # Hitung TF
        tf_entry = {
            term: counter.tf_counter(term, clean_doc)
            for term in query_tokens
        }

        tf_global[doc_key] = tf_entry
        paragraph_tf[doc_key] = tf_entry

        doc_counter += 1

    # -------------------------------
    # HITUNG DF & IDF
    # -------------------------------
    N = len(clean_docs)

    df_terms = {}
    idf_terms = {}

    for term in query_tokens:
        df_value = counter.calc_df(term, clean_docs)
        df_terms[term] = df_value

        idf_terms[term] = (
            counter.calc_idf(N, df_value)
            if df_value > 0 else 0
        )

    # -------------------------------
    # SIMPAN HASIL
    # -------------------------------
    tf_paragraph[paragraph_key] = paragraph_tf
    df_all[paragraph_key] = df_terms
    idf_paragraph[paragraph_key] = idf_terms

    # -------------------------------
    # HITUNG TF-IDF
    # -------------------------------
    tfidf_paragraph[paragraph_key] = {
        doc_key: {
            term: paragraph_tf[doc_key][term] * idf_terms[term]
            for term in query_tokens
        }
        for doc_key in paragraph_tf
    }

Processing P1/5 : 1
  Split into 4 documents
Processing P2/5 : 2
  Split into 8 documents
Processing P3/5 : 3
  Split into 10 documents
Processing P4/5 : 4
  Split into 6 documents
Processing P5/5 : 5
  Split into 10 documents

In [60]:
# print(tf_paragraph)
# print(tfidf_paragraph)
# print(df_all)
for para_key, docs in tfidf_paragraph.items():
    print(f"\n{'='*40}")
    print(f"  {para_key}")
    print(f"{'='*40}")
    
    print("\n[TF]")
    display(pd.DataFrame(tf_paragraph[para_key]).round(3))
    
    print("\n[DF]")
    display(pd.Series(df_all[para_key]).round(3).to_frame("df"))
    
    print("\n[IDF]")
    display(pd.Series(idf_paragraph[para_key]).round(3).to_frame("idf"))
    
    print("\n[TF-IDF]")
    display(pd.DataFrame(tfidf_paragraph[para_key]).round(3))
    
    # print("\n[VSM Cosine Similarity]")
    # para_vsm = {dk: vsm_scores[dk] for dk in docs}
    # display(pd.Series(para_vsm).round(3).to_frame("score"))

========================================
  P1
========================================

[TF]

         QUERY  D1  D2  D3  D4
anthrop      1   1   0   0   1
claud        1   1   0   0   0
mytho        1   1   0   2   0
risk         1   0   0   0   0
pose         1   0   1   0   0

[DF]

         df
anthrop   2
claud     1
mytho     2
risk      0
pose      1

[IDF]

           idf
anthrop  1.693
claud    2.386
mytho    1.693
risk     0.000
pose     2.386

[TF-IDF]

         QUERY     D1     D2     D3     D4
anthrop  1.693  1.693  0.000  0.000  1.693
claud    2.386  2.386  0.000  0.000  0.000
mytho    1.693  1.693  0.000  3.386  0.000
risk     0.000  0.000  0.000  0.000  0.000
pose     2.386  0.000  2.386  0.000  0.000

========================================
  P2
========================================

[TF]

         QUERY  D5  D6  D7  D8  D9  D10  D11  D12
anthrop      1   1   1   0   0   1    0    1    1
claud        1   1   0   0   0   1    0    0    0
mytho        1   1   1   1   0   0    0    1    0
risk         1   0   0   0   0   0    0    0    1
pose         1   0   0   0   0   0    0    0    0

[DF]

         df
anthrop   5
claud     2
mytho     4
risk      1
pose      0

[IDF]

           idf
anthrop  1.470
claud    2.386
mytho    1.693
risk     3.079
pose     0.000

[TF-IDF]

         QUERY     D5     D6     D7   D8     D9  D10    D11    D12
anthrop  1.470  1.470  1.470  0.000  0.0  1.470  0.0  1.470  1.470
claud    2.386  2.386  0.000  0.000  0.0  2.386  0.0  0.000  0.000
mytho    1.693  1.693  1.693  1.693  0.0  0.000  0.0  1.693  0.000
risk     3.079  0.000  0.000  0.000  0.0  0.000  0.0  0.000  3.079
pose     0.000  0.000  0.000  0.000  0.0  0.000  0.0  0.000  0.000

========================================
  P3
========================================

[TF]

         QUERY  D13  D14  D15  D16  D17  D18  D19  D20  D21  D22
anthrop      1    1    1    0    0    0    0    0    0    1    0
claud        1    0    0    0    0    0    0    0    0    0    0
mytho        1    0    1    0    0    0    1    0    0    1    0
risk         1    0    0    0    0    0    0    0    1    0    0
pose         1    0    0    0    0    0    0    0    0    0    0

[DF]

         df
anthrop   3
claud     0
mytho     3
risk      1
pose      0

[IDF]

           idf
anthrop  2.204
claud    0.000
mytho    2.204
risk     3.303
pose     0.000

[TF-IDF]

         QUERY    D13    D14  D15  D16  D17    D18  D19    D20    D21  D22
anthrop  2.204  2.204  2.204  0.0  0.0  0.0  0.000  0.0  0.000  2.204  0.0
claud    0.000  0.000  0.000  0.0  0.0  0.0  0.000  0.0  0.000  0.000  0.0
mytho    2.204  0.000  2.204  0.0  0.0  0.0  2.204  0.0  0.000  2.204  0.0
risk     3.303  0.000  0.000  0.0  0.0  0.0  0.000  0.0  3.303  0.000  0.0
pose     0.000  0.000  0.000  0.0  0.0  0.0  0.000  0.0  0.000  0.000  0.0

========================================
  P4
========================================

[TF]

         QUERY  D23  D24  D25  D26  D27  D28
anthrop      1    0    0    0    0    0    0
claud        1    0    0    0    0    0    0
mytho        1    1    0    1    0    1    0
risk         1    0    0    0    0    0    0
pose         1    0    0    0    0    0    0

[DF]

         df
anthrop   0
claud     0
mytho     3
risk      0
pose      0

[IDF]

           idf
anthrop  0.000
claud    0.000
mytho    1.693
risk     0.000
pose     0.000

[TF-IDF]

         QUERY    D23  D24    D25  D26    D27  D28
anthrop  0.000  0.000  0.0  0.000  0.0  0.000  0.0
claud    0.000  0.000  0.0  0.000  0.0  0.000  0.0
mytho    1.693  1.693  0.0  1.693  0.0  1.693  0.0
risk     0.000  0.000  0.0  0.000  0.0  0.000  0.0
pose     0.000  0.000  0.0  0.000  0.0  0.000  0.0

========================================
  P5
========================================

[TF]

         QUERY  D29  D30  D31  D32  D33  D34  D35  D36  D37  D38
anthrop      1    0    0    0    0    1    0    0    0    1    0
claud        1    0    0    0    0    0    0    0    0    0    0
mytho        1    0    0    0    1    0    0    0    0    0    0
risk         1    0    0    0    0    0    0    0    0    1    0
pose         1    0    0    0    0    0    0    0    0    0    0

[DF]

         df
anthrop   2
claud     0
mytho     1
risk      1
pose      0

[IDF]

           idf
anthrop  2.609
claud    0.000
mytho    3.303
risk     3.303
pose     0.000

[TF-IDF]

         QUERY  D29  D30  D31    D32    D33  D34  D35  D36    D37  D38
anthrop  2.609  0.0  0.0  0.0  0.000  2.609  0.0  0.0  0.0  2.609  0.0
claud    0.000  0.0  0.0  0.0  0.000  0.000  0.0  0.0  0.0  0.000  0.0
mytho    3.303  0.0  0.0  0.0  3.303  0.000  0.0  0.0  0.0  0.000  0.0
risk     3.303  0.0  0.0  0.0  0.000  0.000  0.0  0.0  0.0  3.303  0.0
pose     0.000  0.0  0.0  0.0  0.000  0.000  0.0  0.0  0.0  0.000  0.0

## hitung jarak dokumen dan query

akar sigma W ** 2

In [61]:
jarak = {}

for para_key, docs in tfidf_paragraph.items():
    jarak_per_paragraph = {}
    print(f"\n{'='*40}")
    print(f"  {para_key}")
    print(f"{'='*40}")
    
    # print("\n[TF-IDF]")
    # display(pd.DataFrame(tfidf_paragraph[para_key]).round(3))
    print("akar sum kuadrat")
    for doc_key, W in tfidf_paragraph[para_key].items():
        sum_of_squares = sum(value ** 2 for value in W.values())
        magnitude = sum_of_squares ** 0.5
        
        print(f"{doc_key}: {magnitude:.3f}")
        jarak_per_paragraph[doc_key] = magnitude
    
    jarak[para_key] = jarak_per_paragraph

========================================
  P1
========================================
akar sum kuadrat
QUERY: 4.138
D1: 3.381
D2: 2.386
D3: 3.386
D4: 1.693

========================================
  P2
========================================
akar sum kuadrat
QUERY: 4.495
D5: 3.274
D6: 2.242
D7: 1.693
D8: 0.000
D9: 2.803
D10: 0.000
D11: 2.242
D12: 3.412

========================================
  P3
========================================
akar sum kuadrat
QUERY: 4.541
D13: 2.204
D14: 3.117
D15: 0.000
D16: 0.000
D17: 0.000
D18: 2.204
D19: 0.000
D20: 3.303
D21: 3.117
D22: 0.000

========================================
  P4
========================================
akar sum kuadrat
QUERY: 1.693
D23: 1.693
D24: 0.000
D25: 1.693
D26: 0.000
D27: 1.693
D28: 0.000

========================================
  P5
========================================
akar sum kuadrat
QUERY: 5.350
D29: 0.000
D30: 0.000
D31: 0.000
D32: 3.303
D33: 2.609
D34: 0.000
D35: 0.000
D36: 0.000
D37: 4.209
D38: 0.000

In [62]:
for para_key, docs in jarak.items():
    print(f"\n{'='*40}")
    print(f"  {para_key}")
    print(f"{'='*40}")
    
    print("\n[Jarak]")
    display(pd.Series(docs).round(3).to_frame("jarak").T)

========================================
  P1
========================================

[Jarak]

       QUERY     D1     D2     D3     D4
jarak  4.138  3.381  2.386  3.386  1.693

========================================
  P2
========================================

[Jarak]

       QUERY     D5     D6     D7   D8     D9  D10    D11    D12
jarak  4.495  3.274  2.242  1.693  0.0  2.803  0.0  2.242  3.412

========================================
  P3
========================================

[Jarak]

       QUERY    D13    D14  D15  D16  D17    D18  D19    D20    D21  D22
jarak  4.541  2.204  3.117  0.0  0.0  0.0  2.204  0.0  3.303  3.117  0.0

========================================
  P4
========================================

[Jarak]

       QUERY    D23  D24    D25  D26    D27  D28
jarak  1.693  1.693  0.0  1.693  0.0  1.693  0.0

========================================
  P5
========================================

[Jarak]

       QUERY  D29  D30  D31    D32    D33  D34  D35  D36    D37  D38
jarak   5.35  0.0  0.0  0.0  3.303  2.609  0.0  0.0  0.0  4.209  0.0

In [63]:
print(tfidf_paragraph)
for para_key, docs in tfidf_paragraph.items():
    print(f"\n{'='*40}")
    print(f"  {para_key}")
    print(f"{'='*40}")
    display(pd.DataFrame(tfidf_paragraph[para_key]).round(3))

{'P1': {'QUERY': {'anthrop': 1.6931471805599454, 'claud': 2.386294361119891, 'mytho': 1.6931471805599454, 'risk': 0, 'pose': 2.386294361119891}, 'D1': {'anthrop': 1.6931471805599454, 'claud': 2.386294361119891, 'mytho': 1.6931471805599454, 'risk': 0, 'pose': 0.0}, 'D2': {'anthrop': 0.0, 'claud': 0.0, 'mytho': 0.0, 'risk': 0, 'pose': 2.386294361119891}, 'D3': {'anthrop': 0.0, 'claud': 0.0, 'mytho': 3.386294361119891, 'risk': 0, 'pose': 0.0}, 'D4': {'anthrop': 1.6931471805599454, 'claud': 0.0, 'mytho': 0.0, 'risk': 0, 'pose': 0.0}}, 'P2': {'QUERY': {'anthrop': 1.4700036292457357, 'claud': 2.386294361119891, 'mytho': 1.6931471805599454, 'risk': 3.0794415416798357, 'pose': 0}, 'D5': {'anthrop': 1.4700036292457357, 'claud': 2.386294361119891, 'mytho': 1.6931471805599454, 'risk': 0.0, 'pose': 0}, 'D6': {'anthrop': 1.4700036292457357, 'claud': 0.0, 'mytho': 1.6931471805599454, 'risk': 0.0, 'pose': 0}, 'D7': {'anthrop': 0.0, 'claud': 0.0, 'mytho': 1.6931471805599454, 'risk': 0.0, 'pose': 0}, 'D8': {'anthrop': 0.0, 'claud': 0.0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}, 'D9': {'anthrop': 1.4700036292457357, 'claud': 2.386294361119891, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}, 'D10': {'anthrop': 0.0, 'claud': 0.0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}, 'D11': {'anthrop': 1.4700036292457357, 'claud': 0.0, 'mytho': 1.6931471805599454, 'risk': 0.0, 'pose': 0}, 'D12': {'anthrop': 1.4700036292457357, 'claud': 0.0, 'mytho': 0.0, 'risk': 3.0794415416798357, 'pose': 0}}, 'P3': {'QUERY': {'anthrop': 2.203972804325936, 'claud': 0, 'mytho': 2.203972804325936, 'risk': 3.302585092994046, 'pose': 0}, 'D13': {'anthrop': 2.203972804325936, 'claud': 0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}, 'D14': {'anthrop': 2.203972804325936, 'claud': 0, 'mytho': 2.203972804325936, 'risk': 0.0, 'pose': 0}, 'D15': {'anthrop': 0.0, 'claud': 0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}, 'D16': {'anthrop': 0.0, 'claud': 0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}, 'D17': {'anthrop': 0.0, 'claud': 0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}, 'D18': {'anthrop': 0.0, 'claud': 0, 'mytho': 2.203972804325936, 'risk': 0.0, 'pose': 0}, 'D19': {'anthrop': 0.0, 'claud': 0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}, 'D20': {'anthrop': 0.0, 'claud': 0, 'mytho': 0.0, 'risk': 3.302585092994046, 'pose': 0}, 'D21': {'anthrop': 2.203972804325936, 'claud': 0, 'mytho': 2.203972804325936, 'risk': 0.0, 'pose': 0}, 'D22': {'anthrop': 0.0, 'claud': 0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}}, 'P4': {'QUERY': {'anthrop': 0, 'claud': 0, 'mytho': 1.6931471805599454, 'risk': 0, 'pose': 0}, 'D23': {'anthrop': 0, 'claud': 0, 'mytho': 1.6931471805599454, 'risk': 0, 'pose': 0}, 'D24': {'anthrop': 0, 'claud': 0, 'mytho': 0.0, 'risk': 0, 'pose': 0}, 'D25': {'anthrop': 0, 'claud': 0, 'mytho': 1.6931471805599454, 'risk': 0, 'pose': 0}, 'D26': {'anthrop': 0, 'claud': 0, 'mytho': 0.0, 'risk': 0, 'pose': 0}, 'D27': {'anthrop': 0, 'claud': 0, 'mytho': 1.6931471805599454, 'risk': 0, 'pose': 0}, 'D28': {'anthrop': 0, 'claud': 0, 'mytho': 0.0, 'risk': 0, 'pose': 0}}, 'P5': {'QUERY': {'anthrop': 2.6094379124341005, 'claud': 0, 'mytho': 3.302585092994046, 'risk': 3.302585092994046, 'pose': 0}, 'D29': {'anthrop': 0.0, 'claud': 0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}, 'D30': {'anthrop': 0.0, 'claud': 0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}, 'D31': {'anthrop': 0.0, 'claud': 0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}, 'D32': {'anthrop': 0.0, 'claud': 0, 'mytho': 3.302585092994046, 'risk': 0.0, 'pose': 0}, 'D33': {'anthrop': 2.6094379124341005, 'claud': 0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}, 'D34': {'anthrop': 0.0, 'claud': 0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}, 'D35': {'anthrop': 0.0, 'claud': 0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}, 'D36': {'anthrop': 0.0, 'claud': 0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}, 'D37': {'anthrop': 2.6094379124341005, 'claud': 0, 'mytho': 0.0, 'risk': 3.302585092994046, 'pose': 0}, 'D38': {'anthrop': 0.0, 'claud': 0, 'mytho': 0.0, 'risk': 0.0, 'pose': 0}}}

========================================
  P1
========================================

         QUERY     D1     D2     D3     D4
anthrop  1.693  1.693  0.000  0.000  1.693
claud    2.386  2.386  0.000  0.000  0.000
mytho    1.693  1.693  0.000  3.386  0.000
risk     0.000  0.000  0.000  0.000  0.000
pose     2.386  0.000  2.386  0.000  0.000

========================================
  P2
========================================

         QUERY     D5     D6     D7   D8     D9  D10    D11    D12
anthrop  1.470  1.470  1.470  0.000  0.0  1.470  0.0  1.470  1.470
claud    2.386  2.386  0.000  0.000  0.0  2.386  0.0  0.000  0.000
mytho    1.693  1.693  1.693  1.693  0.0  0.000  0.0  1.693  0.000
risk     3.079  0.000  0.000  0.000  0.0  0.000  0.0  0.000  3.079
pose     0.000  0.000  0.000  0.000  0.0  0.000  0.0  0.000  0.000

========================================
  P3
========================================

         QUERY    D13    D14  D15  D16  D17    D18  D19    D20    D21  D22
anthrop  2.204  2.204  2.204  0.0  0.0  0.0  0.000  0.0  0.000  2.204  0.0
claud    0.000  0.000  0.000  0.0  0.0  0.0  0.000  0.0  0.000  0.000  0.0
mytho    2.204  0.000  2.204  0.0  0.0  0.0  2.204  0.0  0.000  2.204  0.0
risk     3.303  0.000  0.000  0.0  0.0  0.0  0.000  0.0  3.303  0.000  0.0
pose     0.000  0.000  0.000  0.0  0.0  0.0  0.000  0.0  0.000  0.000  0.0

========================================
  P4
========================================

         QUERY    D23  D24    D25  D26    D27  D28
anthrop  0.000  0.000  0.0  0.000  0.0  0.000  0.0
claud    0.000  0.000  0.0  0.000  0.0  0.000  0.0
mytho    1.693  1.693  0.0  1.693  0.0  1.693  0.0
risk     0.000  0.000  0.0  0.000  0.0  0.000  0.0
pose     0.000  0.000  0.0  0.000  0.0  0.000  0.0

========================================
  P5
========================================

         QUERY  D29  D30  D31    D32    D33  D34  D35  D36    D37  D38
anthrop  2.609  0.0  0.0  0.0  0.000  2.609  0.0  0.0  0.0  2.609  0.0
claud    0.000  0.0  0.0  0.0  0.000  0.000  0.0  0.0  0.0  0.000  0.0
mytho    3.303  0.0  0.0  0.0  3.303  0.000  0.0  0.0  0.0  0.000  0.0
risk     3.303  0.0  0.0  0.0  0.000  0.000  0.0  0.0  0.0  3.303  0.0
pose     0.000  0.0  0.0  0.0  0.000  0.000  0.0  0.0  0.0  0.000  0.0

## hitung dot product

In [64]:
dot_product = {}
for para_key, docs in tfidf_paragraph.items():
    # print(f"\n{'='*40}")
    # print(f"  {para_key}")
    # print(f"{'='*40}")
    # display(pd.DataFrame(tfidf_paragraph[para_key]).round(3))
    dot_product_paragraph = {}
    for doc_key, W in tfidf_paragraph[para_key].items():
        # print(f"Document: {doc_key}")
        # print(f"TF-IDF Vector: {W}")
        Q = tfidf_paragraph[para_key].get("QUERY", {})
        # print(f"Query TF-IDF Vector: {Q}")
        dot_product_value = sum(W.get(term, 0) * Q.get(term, 0) for term in Q)
        dot_product_paragraph[doc_key] = dot_product_value
        
    dot_product[para_key] = dot_product_paragraph
    
print(dot_product)

{'P1': {'QUERY': 17.122296305901358, 'D1': 11.427895527988772, 'D2': 5.694400777912588, 'D3': 5.733494750076185, 'D4': 2.8667473750380923}, 'P2': {'QUERY': 20.205019031569798, 'D5': 10.722058822946314, 'D6': 5.027658045033727, 'D7': 2.8667473750380923, 'D8': 0.0, 'D9': 7.855311447908222, 'D10': 0.0, 'D11': 5.027658045033727, 'D12': 11.643870878619119}, 'P3': {'QUERY': 20.62206054088315, 'D13': 4.85749612220833, 'D14': 9.71499224441666, 'D15': 0.0, 'D16': 0.0, 'D17': 0.0, 'D18': 4.85749612220833, 'D19': 0.0, 'D20': 10.907068296466491, 'D21': 9.71499224441666, 'D22': 0.0}, 'P4': {'QUERY': 2.8667473750380923, 'D23': 2.8667473750380923, 'D24': 0.0, 'D25': 2.8667473750380923, 'D26': 0.0, 'D27': 2.8667473750380923, 'D28': 0.0}, 'P5': {'QUERY': 28.623302811781418, 'D29': 0.0, 'D30': 0.0, 'D31': 0.0, 'D32': 10.907068296466491, 'D33': 6.8091662188484365, 'D34': 0.0, 'D35': 0.0, 'D36': 0.0, 'D37': 17.716234515314927, 'D38': 0.0}}

In [ ]:
cosine_similarity = {}
print("\n[dot product]")
for para_key, docs in dot_product.items():
    cosine_similarity_per_paragraph = {}
    print(f"\n{'='*40}")
    print(f"  {para_key}")
    print(f"{'='*40}")
    
    # print(docs)
    for term in docs:
        
        similarity = counter.calc_cosine_similarity(docs[term], jarak[para_key].get(term, 0.0), jarak[para_key].get("QUERY", 0.0))
        # print(f"{similarity:.3f}")
        cosine_similarity_per_paragraph[term] = similarity

    cosine_similarity[para_key] = cosine_similarity_per_paragraph

    # display(pd.Series(cosine_similarity_per_paragraph).round(3).to_frame("cosine_similarity").T)

[dot product]

========================================
  P1
========================================

                   QUERY     D1     D2     D3     D4
cosine_similarity    1.0  0.817  0.577  0.409  0.409

========================================
  P2
========================================

                   QUERY     D5     D6     D7   D8     D9  D10    D11    D12
cosine_similarity    1.0  0.728  0.499  0.377  0.0  0.624  0.0  0.499  0.759

========================================
  P3
========================================

,QUERY,D13,D14,D15,D16,D17,D18,D19,D20,D21,D22
cosine_similarity,1.0,0.485,0.686,0.0,0.0,0.0,0.485,0.0,0.727,0.686,0.0

========================================
  P4
========================================

                   QUERY  D23  D24  D25  D26  D27  D28
cosine_similarity    1.0  1.0  0.0  1.0  0.0  1.0  0.0

========================================
  P5
========================================

,QUERY,D29,D30,D31,D32,D33,D34,D35,D36,D37,D38
cosine_similarity,1.0,0.0,0.0,0.0,0.617,0.488,0.0,0.0,0.0,0.787,0.0

# ranking dokumen

In [76]:
top_2_results = {}  # Wadah untuk menyimpan hasil akhir

for para_key, docs in jarak.items():
    print(f"\n{'='*40}")
    print(f"  {para_key}")
    print(f"{'='*40}")
    
    # Hapus QUERY agar tidak ikut terhitung
    cosine_similarity[para_key].pop("QUERY", None)
    
    # Urutkan berdasarkan skor tertinggi
    rank = dict(sorted(cosine_similarity[para_key].items(), key=lambda item: item[1], reverse=True))
    
    # Ambil 2 teratas menggunakan slicing list dan ubah kembali ke dict
    top_2 = dict(list(rank.items())[:2])
    top_2_results[para_key] = top_2 # Simpan ke variabel luar
    
    print("\n[Top 2 Rank]")
    for term, score in top_2.items():
        print(f"  {term}: {score:.3f}")

# Sekarang variabel 'top_2_results' berisi dokumen terbaik untuk setiap para_key

========================================
  P1
========================================

[Top 2 Rank]
  D1: 0.817
  D2: 0.577

========================================
  P2
========================================

[Top 2 Rank]
  D12: 0.759
  D5: 0.728

========================================
  P3
========================================

[Top 2 Rank]
  D20: 0.727
  D14: 0.686

========================================
  P4
========================================

[Top 2 Rank]
  D23: 1.000
  D25: 1.000

========================================
  P5
========================================

[Top 2 Rank]
  D37: 0.787
  D32: 0.617