# Prerequisites

In [2]:
%pip install -r requirements.txt

Requirement already satisfied: altair==6.0.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (6.0.0)
Requirement already satisfied: attrs==26.1.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (26.1.0)
Requirement already satisfied: blinker==1.9.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (1.9.0)
Requirement already satisfied: cachetools==7.0.5 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (7.0.5)
Requirement already satisfied: certifi==2026.2.25 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 5)) (2026.2.25)
Requirement already satisfied: charset-normalizer==3.4.7 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 6)) (3.4.7)
Requirement already satisfied: click==8.3.2 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 7)) (8.3.2)
Requirement already satisfied: colorama==0.4.6 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 8)) (0.4.6)
Requirement already satisfied: gitdb==4.0.12 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 9)) (4.0.12)
Requirement already satisfied: GitPython==3.1.46 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 10)) (3.1.46)
Requirement already satisfied: idna==3.11 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 11)) (3.11)
Requirement already satisfied: Jinja2==3.1.6 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 12)) (3.1.6)
Requirement already satisfied: joblib==1.5.3 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 13)) (1.5.3)
Requirement already satisfied: jsonschema==4.26.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 14)) (4.26.0)
Requirement already satisfied: jsonschema-specifications==2025.9.1 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 15)) (2025.9.1)
Requirement already satisfied: MarkupSafe==3.0.3 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 16)) (3.0.3)
Requirement already satisfied: narwhals==2.19.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 17)) (2.19.0)
Requirement already satisfied: nltk==3.9.4 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 18)) (3.9.4)
Requirement already satisfied: numpy==2.4.4 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 19)) (2.4.4)
Requirement already satisfied: packaging==26.1 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 20)) (26.1)
Requirement already satisfied: pandas==3.0.2 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 21)) (3.0.2)
Requirement already satisfied: pillow==12.2.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 22)) (12.2.0)
Requirement already satisfied: protobuf==7.34.1 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 23)) (7.34.1)
Requirement already satisfied: pyarrow==23.0.1 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 24)) (23.0.1)
Requirement already satisfied: pydeck==0.9.2 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 25)) (0.9.2)
Requirement already satisfied: python-dateutil==2.9.0.post0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 26)) (2.9.0.post0)
Requirement already satisfied: referencing==0.37.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 27)) (0.37.0)
Requirement already satisfied: regex==2026.4.4 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 28)) (2026.4.4)
Requirement already satisfied: requests==2.33.1 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 29)) (2.33.1)
Requirement already satisfied: rpds-py==0.30.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 30)) (0.30.0)
Requirement already satisfied: scikit-learn==1.8.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 31)) (1.8.0)
Requirement already satisfied: scipy==1.17.1 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 32)) (1.17.1)
Requirement already satisfied: six==1.17.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 33)) (1.17.0)
Requirement already satisfied: smmap==5.0.3 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 34)) (5.0.3)
Requirement already satisfied: streamlit==1.56.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 35)) (1.56.0)
Requirement already satisfied: tenacity==9.1.4 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 36)) (9.1.4)
Requirement already satisfied: threadpoolctl==3.6.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 37)) (3.6.0)
Requirement already satisfied: toml==0.10.2 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 38)) (0.10.2)
Requirement already satisfied: tornado==6.5.5 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 39)) (6.5.5)
Requirement already satisfied: tqdm==4.67.3 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 40)) (4.67.3)
Requirement already satisfied: typing_extensions==4.15.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 41)) (4.15.0)
Requirement already satisfied: tzdata==2026.1 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 42)) (2026.1)
Requirement already satisfied: urllib3==2.6.3 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 43)) (2.6.3)
Requirement already satisfied: watchdog==6.0.0 in /mnt/d/kuliah/SMT 4/STKI/summaryzation/.venv/lib/python3.12/site-packages (from -r requirements.txt (line 44)) (6.0.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Auto-reload module eksternal setiap cell dijalankan ulang
%load_ext autoreload
%autoreload 2

# Load file artikel

In [16]:
from pathlib import Path
import pandas as pd

article_path = Path("article/test.md")
article = article_path.read_text(encoding="utf-8")

print(f"Loaded: {article_path} ({len(article)} karakter)")
print(article)  # preview

Loaded: article/test.md (6555 karakter)
# Nature and outdoors can help boost your health - here's how

## How 20 minutes of nature can boost your health

![](https://static.files.bbci.co.uk/bbcdotcom/web/20260427-074339-4d487e3684-web-3.2.0-4/grey-placeholder.png)!Getty Images A wide, front view angle shot of a family and their dog walking through a woodland forest in Northumberland, Northeastern England during the Covid-19 pandemic.Getty Images

Spending just 20 minutes in nature can trigger measurable changes inside your body

If you've ever felt calmer after a walk in the park or a stroll through the woods, it's not your imagination - it's biology.

Being outdoors can trigger measurable changes inside your body from lowering stress hormones, easing blood pressure and even improving your gut health.

You don't have to hike for hours to feel these benefits as maximum impact happens after just 20 minutes, so even a lunchtime walk to the park and a sandwich on a bench a few times a week can benefit your body and mind.

Here are four ways that being among nature can help improve your health.

![](https://static.files.bbci.co.uk/bbcdotcom/web/20260427-074339-4d487e3684-web-3.2.0-4/grey-placeholder.png)!Thin brown banner with headshots of Drs Chris and Xand van Tulleken and the What's up Doctors branding with the wording "Drs Chris and Xand van Tulleken are on a mission to help us take better care of ourselves. Listen to What's Up Docs? on BBC Sounds or wherever you get your BBC podcasts."

Drs Chris and Xand van Tulleken are on a mission to help us take better care of ourselves. Listen to What's Up Docs? on BBC Sounds or wherever you get your BBC podcasts."

## 1\. You unconsciously relax

When you see green trees, smell pine and hear gentle rustling leaves or the sound of birdsong, your autonomic nervous system - a network of nerves controlling unconscious processes - responds instantly.

This can happen on a visit to the local park.

"We see changes in the body such as a lowering of blood pressure, a change in your heart rate variability and your heart beats slower - all associated with physiological calming," Baroness Kathy Willis, a biodiversity professor at Oxford University, told BBC Radio 4's What's Up Docs? podcast.

A UK study, involving nearly 20,000 people, found that those who spent at least a total of 120 minutes every week in greenery were significantly more likely to report good health and higher psychological well-being.

The evidence for the benefits of spending time in nature is compelling enough that some areas have trialled so called green social prescribing connecting people with nature to improve their phsyical and mental health, with a positive impact on happiness and wellbeing.

## 2\. Your hormones reboot

Your body's hormonal system also joins in the relaxation act.

Willis says that spending time outdoors triggers our endocrine system and lowers levels of cortisol and adrenaline - the hormones that surge when you're stressed or anxious.

"A study found that people in a hotel room for three days who were breathing in Hinoki (Japanese cypress) oil saw a big drop in the adrenaline hormone and a large increase in natural killer cells in their blood."

Natural killer cells are cells that tackle viruses in the body. The participants in the study still had elevated natural killer cells in their body two weeks after inhaling the smell.

Essentially nature "calms what needs calming and strengthens what needs strengthening," is how Prof Ming Kuo from the University of Illinois at Urbana-Champaign, summed it up to the BBC.

"A three-day weekend in nature has a huge impact on our virus fighting apparatus and even a month later it can be 24% above baseline."

Studies also show smaller but still persistent effects from shorter periods spent in nature, she says.

## 3\. Smell is a powerful sense

Smelling nature is just as powerful as seeing and hearing it.

The scent of trees and soil is full of organic compounds released by plants and "when you breathe them in, some molecules pass into the bloodstream."

Willis says pine is a good example of this as the smell of a pine forest can make you calmer within just 90 seconds and that effect lasts for about 10 minutes.

You may think that the relaxing effect of nature is all in your mind, but another study found that even very young babies with no memory associated with particular smells, still calmed down when another scent associated with calming, limonene was puffed into the room they were in.

## 4\. Gets good bacteria into your gut

![](https://static.files.bbci.co.uk/bbcdotcom/web/20260427-074339-4d487e3684-web-3.2.0-4/grey-placeholder.png)!Getty Images Focus is on the wellies of two children - a girl and a boy, using a small trowel to plant seeds in a long planter trough.Getty Images

Touching soil can help your body adopt good bacteria

As well as soothing your mind, nature can also help boost your microbiome as soil and plants are full of good bacteria.

"They're the same kinds of good bacteria we pay for in probiotics or drinks," Willis explains.

Prof Ming Kuo has studied the effect on factors such as infection susceptibility as well as mental health and says breathing in certain ones have the potential to boost your mood; and the antimicrobial chemicals released by plants – called phytoncides – could help fight disease.

Dr Chris van Tulleken says as an infection scientist he sees nature as a positively challenging environment that "tickles your immune system".

He gets his children to play with dirt in the forest which then enters their system through the nose or mouth.

## Bring nature to you

![](https://static.files.bbci.co.uk/bbcdotcom/web/20260427-074339-4d487e3684-web-3.2.0-4/grey-placeholder.png)!Getty Images Laptop showing nature wallpaper on bedGetty Images

Even having a nature screensaver on your laptop can help you relax

Of course, not everyone can head into the woods on a whim but the good news is, you don't have to.

Even small touches of nature at home can make a difference, according to Willis.

Visually, flowers such as white or yellow roses have been shown to create the greatest calming effect on brain activity.

When it comes to smell, use a diffuser with essential oils like pinene which can help you feel calm.

And if all else fails, even a photo of a forest can help.

Research shows that looking at pictures of nature on your laptop or simply gazing out at something green can trigger the same calming brainwave changes and reduce stress.

"Every bit seems to help," says Prof Ming Kuo.

# Proses

## Pecah menjadi beberapa paragraph

In [17]:
import importlib
import preprocess

# Pastikan module eksternal memakai versi terbaru dari file .py
importlib.reload(preprocess)

# ambil query dari heading pertama markdown
first_nonempty_line = next((line.strip() for line in article.splitlines() if line.strip()), "")
# print(f"First non-empty line: {first_nonempty_line}")
query = first_nonempty_line.lstrip("#").strip()
print(f"Query: {query}")
query_tokens = preprocess.preProcess(query)
print(f"Query Tokens: {query_tokens}\n")

paragraphs = preprocess.splitParagraph(article)
print(f"Split into {len(paragraphs)} paragraphs")

Query: Nature and outdoors can help boost your health - here's how
Query Tokens: ['natur', 'outdoor', 'help', 'boost', 'health']

Split into 7 paragraphs

[nltk_data] Downloading package punkt to /home/juana/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

## Proses setiap Paragraph

In [18]:
import preprocess
import counter

# ===============================
# STORAGE
# ===============================
tf_global = {}          # TF semua dokumen
tf_paragraph = {}       # TF per paragraph
df_all = {}             # DF per paragraph
idf_paragraph = {}      # IDF per paragraph
tfidf_paragraph = {}    # TF-IDF per paragraph


doc_counter = 1

# ===============================
# MAIN LOOP
# ===============================
for i, (title, content) in enumerate(paragraphs.items(), start=1):
    
    paragraph_key = f"P{i}"
    print(f"Processing {paragraph_key}/{len(paragraphs)} : {title}")
    
    docs = preprocess.splitDocument(content)
    print(f"  Split into {len(docs)} documents")
    # -------------------------------
    # PREPROCESS ALL DOCS
    # -------------------------------
    clean_docs = []
    paragraph_tf = {}


    
    # hitung tf dan idf query
    doc_key = "QUERY"
    tf_entry = {
        term: counter.tf_counter(term, query_tokens)
        for term in query_tokens
    }
    tf_global[doc_key] = tf_entry
    paragraph_tf[doc_key] = tf_entry
        
        
    for doc in docs:
        clean_doc = preprocess.preProcess(doc)
        clean_docs.append(clean_doc)

        doc_key = f"D{doc_counter}"

        # Hitung TF
        tf_entry = {
            term: counter.tf_counter(term, clean_doc)
            for term in query_tokens
        }

        tf_global[doc_key] = tf_entry
        paragraph_tf[doc_key] = tf_entry

        doc_counter += 1

    # -------------------------------
    # HITUNG DF & IDF
    # -------------------------------
    N = len(clean_docs)

    df_terms = {}
    idf_terms = {}

    for term in query_tokens:
        df_value = counter.calc_df(term, clean_docs)
        df_terms[term] = df_value

        idf_terms[term] = (
            counter.calc_idf(N, df_value)
            if df_value > 0 else 0
        )

    # -------------------------------
    # SIMPAN HASIL
    # -------------------------------
    tf_paragraph[paragraph_key] = paragraph_tf
    df_all[paragraph_key] = df_terms
    idf_paragraph[paragraph_key] = idf_terms

    # -------------------------------
    # HITUNG TF-IDF
    # -------------------------------
    tfidf_paragraph[paragraph_key] = {
        doc_key: {
            term: paragraph_tf[doc_key][term] * idf_terms[term]
            for term in query_tokens
        }
        for doc_key in paragraph_tf
    }

Processing P1/7 : 1
  Split into 0 documents
Processing P2/7 : 2
  Split into 6 documents
Processing P3/7 : 3
  Split into 5 documents
Processing P4/7 : 4
  Split into 7 documents
Processing P5/7 : 5
  Split into 4 documents
Processing P6/7 : 6
  Split into 6 documents
Processing P7/7 : 7
  Split into 8 documents

In [19]:
# print(tf_paragraph)
# print(tfidf_paragraph)
# print(df_all)
for para_key, docs in tfidf_paragraph.items():
    print(f"\n{'='*40}")
    print(f"  {para_key}")
    print(f"{'='*40}")
    
    print("\n[TF]")
    display(pd.DataFrame(tf_paragraph[para_key]).round(3))
    
    print("\n[DF]")
    display(pd.Series(df_all[para_key]).round(3).to_frame("df"))
    
    # print("\n[IDF]")
    # display(pd.Series(idf_paragraph[para_key]).round(3).to_frame("idf"))
    
    print("\n[TF-IDF]")
    display(pd.DataFrame(tfidf_paragraph[para_key]).round(3))
    
    # print("\n[VSM Cosine Similarity]")
    # para_vsm = {dk: vsm_scores[dk] for dk in docs}
    # display(pd.Series(para_vsm).round(3).to_frame("score"))

========================================
  P1
========================================

[TF]

         QUERY
natur        1
outdoor      1
help         1
boost        1
health       1

[DF]

         df
natur     0
outdoor   0
help      0
boost     0
health    0

[TF-IDF]

         QUERY
natur        0
outdoor      0
help         0
boost        0
health       0

========================================
  P2
========================================

[TF]

         QUERY  D1  D2  D3  D4  D5  D6
natur        1   1   0   0   0   1   0
outdoor      1   0   0   1   0   0   0
help         1   0   0   0   0   1   1
boost        1   0   0   0   0   0   0
health       1   0   0   1   0   1   0

[DF]

         df
natur     2
outdoor   1
help      2
boost     0
health    2

[TF-IDF]

         QUERY     D1   D2     D3   D4     D5     D6
natur    2.099  2.099  0.0  0.000  0.0  2.099  0.000
outdoor  2.792  0.000  0.0  2.792  0.0  0.000  0.000
help     2.099  0.000  0.0  0.000  0.0  2.099  2.099
boost    0.000  0.000  0.0  0.000  0.0  0.000  0.000
health   2.099  0.000  0.0  2.099  0.0  2.099  0.000

========================================
  P3
========================================

[TF]

         QUERY  D7  D8  D9  D10  D11
natur        1   0   0   0    0    2
outdoor      1   0   0   0    0    0
help         1   0   0   0    0    0
boost        1   0   0   0    0    0
health       1   0   0   0    1    1

[DF]

         df
natur     1
outdoor   0
help      0
boost     0
health    2

[TF-IDF]

         QUERY   D7   D8   D9    D10    D11
natur    2.609  0.0  0.0  0.0  0.000  5.219
outdoor  0.000  0.0  0.0  0.0  0.000  0.000
help     0.000  0.0  0.0  0.0  0.000  0.000
boost    0.000  0.0  0.0  0.0  0.000  0.000
health   1.916  0.0  0.0  0.0  1.916  1.916

========================================
  P4
========================================

[TF]

         QUERY  D12  D13  D14  D15  D16  D17  D18
natur        1    0    0    1    2    1    1    1
outdoor      1    0    1    0    0    0    0    0
help         1    0    0    0    0    0    0    0
boost        1    0    0    0    0    0    0    0
health       1    0    0    0    0    0    0    0

[DF]

         df
natur     5
outdoor   1
help      0
boost     0
health    0

[TF-IDF]

         QUERY  D12    D13    D14    D15    D16    D17    D18
natur    1.336  0.0  0.000  1.336  2.673  1.336  1.336  1.336
outdoor  2.946  0.0  2.946  0.000  0.000  0.000  0.000  0.000
help     0.000  0.0  0.000  0.000  0.000  0.000  0.000  0.000
boost    0.000  0.0  0.000  0.000  0.000  0.000  0.000  0.000
health   0.000  0.0  0.000  0.000  0.000  0.000  0.000  0.000

========================================
  P5
========================================

[TF]

         QUERY  D19  D20  D21  D22
natur        1    1    0    0    1
outdoor      1    0    0    0    0
help         1    0    0    0    0
boost        1    0    0    0    0
health       1    0    0    0    0

[DF]

         df
natur     2
outdoor   0
help      0
boost     0
health    0

[TF-IDF]

         QUERY    D19  D20  D21    D22
natur    1.693  1.693  0.0  0.0  1.693
outdoor  0.000  0.000  0.0  0.0  0.000
help     0.000  0.000  0.0  0.0  0.000
boost    0.000  0.000  0.0  0.0  0.000
health   0.000  0.000  0.0  0.0  0.000

========================================
  P6
========================================

[TF]

         QUERY  D23  D24  D25  D26  D27  D28
natur        1    0    1    0    0    1    0
outdoor      1    0    0    0    0    0    0
help         1    1    1    0    1    0    0
boost        1    0    1    0    1    0    0
health       1    0    0    0    1    0    0

[DF]

         df
natur     2
outdoor   0
help      3
boost     2
health    1

[TF-IDF]

         QUERY    D23    D24  D25    D26    D27  D28
natur    2.099  0.000  2.099  0.0  0.000  2.099  0.0
outdoor  0.000  0.000  0.000  0.0  0.000  0.000  0.0
help     1.693  1.693  1.693  0.0  1.693  0.000  0.0
boost    2.099  0.000  2.099  0.0  2.099  0.000  0.0
health   2.792  0.000  0.000  0.0  2.792  0.000  0.0

========================================
  P7
========================================

[TF]

         QUERY  D29  D30  D31  D32  D33  D34  D35  D36
natur        1    1    0    1    0    0    0    1    0
outdoor      1    0    0    0    0    0    0    0    0
help         1    1    0    0    0    1    1    0    1
boost        1    0    0    0    0    0    0    0    0
health       1    0    0    0    0    0    0    0    0

[DF]

         df
natur     3
outdoor   0
help      4
boost     0
health    0

[TF-IDF]

         QUERY    D29  D30    D31  D32    D33    D34    D35    D36
natur    1.981  1.981  0.0  1.981  0.0  0.000  0.000  1.981  0.000
outdoor  0.000  0.000  0.0  0.000  0.0  0.000  0.000  0.000  0.000
help     1.693  1.693  0.0  0.000  0.0  1.693  1.693  0.000  1.693
boost    0.000  0.000  0.0  0.000  0.0  0.000  0.000  0.000  0.000
health   0.000  0.000  0.0  0.000  0.0  0.000  0.000  0.000  0.000

## hitung jarak dokumen dan query

akar sigma W ** 2

In [20]:
jarak = {}

for para_key, docs in tfidf_paragraph.items():
    jarak_per_paragraph = {}
    print(f"\n{'='*40}")
    print(f"  {para_key}")
    print(f"{'='*40}")
    
    # print("\n[TF-IDF]")
    # display(pd.DataFrame(tfidf_paragraph[para_key]).round(3))
    # print("akar sum kuadrat")
    for doc_key, W in tfidf_paragraph[para_key].items():
        sum_of_squares = sum(value ** 2 for value in W.values())
        magnitude = sum_of_squares ** 0.5
        
        print(f"{doc_key}: {magnitude:.3f}")
        jarak_per_paragraph[doc_key] = magnitude
    
    jarak[para_key] = jarak_per_paragraph

========================================
  P1
========================================
QUERY: 0.000

========================================
  P2
========================================
QUERY: 4.583
D1: 2.099
D2: 0.000
D3: 3.493
D4: 0.000
D5: 3.635
D6: 2.099

========================================
  P3
========================================
QUERY: 3.237
D7: 0.000
D8: 0.000
D9: 0.000
D10: 1.916
D11: 5.560

========================================
  P4
========================================
QUERY: 3.235
D12: 0.000
D13: 2.946
D14: 1.336
D15: 2.673
D16: 1.336
D17: 1.336
D18: 1.336

========================================
  P5
========================================
QUERY: 1.693
D19: 1.693
D20: 0.000
D21: 0.000
D22: 1.693

========================================
  P6
========================================
QUERY: 4.412
D23: 1.693
D24: 3.417
D25: 0.000
D26: 3.881
D27: 2.099
D28: 0.000

========================================
  P7
========================================
QUERY: 2.606
D29: 2.606
D30: 0.000
D31: 1.981
D32: 0.000
D33: 1.693
D34: 1.693
D35: 1.981
D36: 1.693

In [21]:
for para_key, docs in jarak.items():
    print(f"\n{'='*40}")
    print(f"  {para_key}")
    print(f"{'='*40}")
    
    print("\n[Jarak]")
    display(pd.Series(docs).round(3).to_frame("jarak").T)

========================================
  P1
========================================

[Jarak]

       QUERY
jarak    0.0

========================================
  P2
========================================

[Jarak]

       QUERY     D1   D2     D3   D4     D5     D6
jarak  4.583  2.099  0.0  3.493  0.0  3.635  2.099

========================================
  P3
========================================

[Jarak]

       QUERY   D7   D8   D9    D10   D11
jarak  3.237  0.0  0.0  0.0  1.916  5.56

========================================
  P4
========================================

[Jarak]

       QUERY  D12    D13    D14    D15    D16    D17    D18
jarak  3.235  0.0  2.946  1.336  2.673  1.336  1.336  1.336

========================================
  P5
========================================

[Jarak]

       QUERY    D19  D20  D21    D22
jarak  1.693  1.693  0.0  0.0  1.693

========================================
  P6
========================================

[Jarak]

       QUERY    D23    D24  D25    D26    D27  D28
jarak  4.412  1.693  3.417  0.0  3.881  2.099  0.0

========================================
  P7
========================================

[Jarak]

       QUERY    D29  D30    D31  D32    D33    D34    D35    D36
jarak  2.606  2.606  0.0  1.981  0.0  1.693  1.693  1.981  1.693

## hitung dot product

In [22]:
dot_product = {}
for para_key, docs in tfidf_paragraph.items():
    # print(f"\n{'='*40}")
    # print(f"  {para_key}")
    # print(f"{'='*40}")
    # display(pd.DataFrame(tfidf_paragraph[para_key]).round(3))
    dot_product_paragraph = {}
    for doc_key, W in tfidf_paragraph[para_key].items():
        # print(f"Document: {doc_key}")
        # print(f"TF-IDF Vector: {W}")
        Q = tfidf_paragraph[para_key].get("QUERY", {})
        # print(f"Query TF-IDF Vector: {Q}")
        dot_product_value = sum(W.get(term, 0) * Q.get(term, 0) for term in Q)
        dot_product_paragraph[doc_key] = dot_product_value
        
    dot_product[para_key] = dot_product_paragraph
    
print(dot_product)

{'P1': {'QUERY': 0}, 'P2': {'QUERY': 21.00644154847092, 'D1': 4.404173538148803, 'D2': 0.0, 'D3': 12.198094472173313, 'D4': 0.0, 'D5': 13.212520614446408, 'D6': 4.404173538148803}, 'P3': {'QUERY': 10.48133638791522, 'D7': 0.0, 'D8': 0.0, 'D9': 0.0, 'D10': 3.672170169066785, 'D11': 17.29050260676366}, 'P4': {'QUERY': 10.464544645566406, 'D12': 0.0, 'D13': 8.678386606307098, 'D14': 1.7861580392593075, 'D15': 3.572316078518615, 'D16': 1.7861580392593075, 'D17': 1.7861580392593075, 'D18': 1.7861580392593075}, 'P5': {'QUERY': 2.8667473750380923, 'D19': 2.8667473750380923, 'D20': 0.0, 'D21': 0.0, 'D22': 2.8667473750380923}, 'P6': {'QUERY': 19.46901538536021, 'D23': 2.8667473750380923, 'D24': 11.6750944513357, 'D25': 0.0, 'D26': 15.064841847211406, 'D27': 4.404173538148803, 'D28': 0.0}, 'P7': {'QUERY': 6.790431904625086, 'D29': 6.790431904625086, 'D30': 0.0, 'D31': 3.923684529586993, 'D32': 0.0, 'D33': 2.8667473750380923, 'D34': 2.8667473750380923, 'D35': 3.923684529586993, 'D36': 2.8667473750380923}}

In [23]:
cosine_similarity = {}
print("\n[dot product]")
for para_key, docs in dot_product.items():
    cosine_similarity_per_paragraph = {}
    print(f"\n{'='*40}")
    print(f"  {para_key}")
    print(f"{'='*40}")
    
    # print(docs)
    for term in docs:
        
        similarity = counter.calc_cosine_similarity(docs[term], jarak[para_key].get(term, 0.0), jarak[para_key].get("QUERY", 0.0))
        # print(f"{similarity:.3f}")
        cosine_similarity_per_paragraph[term] = similarity

    cosine_similarity[para_key] = cosine_similarity_per_paragraph

    display(pd.Series(cosine_similarity_per_paragraph).round(3).to_frame("cosine_similarity").T)

[dot product]

========================================
  P1
========================================

                   QUERY
cosine_similarity    0.0

========================================
  P2
========================================

                   QUERY     D1   D2     D3   D4     D5     D6
cosine_similarity    1.0  0.458  0.0  0.762  0.0  0.793  0.458

========================================
  P3
========================================

                   QUERY   D7   D8   D9    D10    D11
cosine_similarity    1.0  0.0  0.0  0.0  0.592  0.961

========================================
  P4
========================================

                   QUERY  D12    D13    D14    D15    D16    D17    D18
cosine_similarity    1.0  0.0  0.911  0.413  0.413  0.413  0.413  0.413

========================================
  P5
========================================

                   QUERY  D19  D20  D21  D22
cosine_similarity    1.0  1.0  0.0  0.0  1.0

========================================
  P6
========================================

                   QUERY    D23    D24  D25   D26    D27  D28
cosine_similarity    1.0  0.384  0.774  0.0  0.88  0.476  0.0

========================================
  P7
========================================

                   QUERY  D29  D30   D31  D32   D33   D34   D35   D36
cosine_similarity    1.0  1.0  0.0  0.76  0.0  0.65  0.65  0.76  0.65

# ranking dokumen

In [24]:
n = 3
top_n_results = {}  # Wadah untuk menyimpan hasil akhir

for para_key, docs in jarak.items():
    print(f"\n{'='*40}")
    print(f"  {para_key}")
    print(f"{'='*40}")
    
    # Hapus QUERY agar tidak ikut terhitung
    cosine_similarity[para_key].pop("QUERY", None)
    
    # Urutkan berdasarkan skor tertinggi
    rank = dict(sorted(cosine_similarity[para_key].items(), key=lambda item: item[1], reverse=True))
    
    # Ambil n teratas menggunakan slicing list dan ubah kembali ke dict
    top_n = dict(list(rank.items())[:n])
    top_n_results[para_key] = top_n # Simpan ke variabel luar
    
    print(f"\n[Top {n} Rank]")
    for term, score in top_n.items():
        print(f"  {term}: {score:.3f}")

# Sekarang variabel 'top_n_results' berisi dokumen terbaik untuk setiap para_key

========================================
  P1
========================================

[Top 3 Rank]

========================================
  P2
========================================

[Top 3 Rank]
  D5: 0.793
  D3: 0.762
  D1: 0.458

========================================
  P3
========================================

[Top 3 Rank]
  D11: 0.961
  D10: 0.592
  D7: 0.000

========================================
  P4
========================================

[Top 3 Rank]
  D13: 0.911
  D14: 0.413
  D15: 0.413

========================================
  P5
========================================

[Top 3 Rank]
  D19: 1.000
  D22: 1.000
  D20: 0.000

========================================
  P6
========================================

[Top 3 Rank]
  D26: 0.880
  D24: 0.774
  D27: 0.476

========================================
  P7
========================================

[Top 3 Rank]
  D29: 1.000
  D31: 0.760
  D35: 0.760

## Summary

In [ ]:
doc_text_map = {}
doc_counter = 1

for _, content in paragraphs.items():
    docs = preprocess.splitDocument(content)
    for doc in docs:
        doc_key = f"D{doc_counter}"
        doc_text_map[doc_key] = doc.strip()
        doc_counter += 1

# Buat summary dari top_n_results
summary_per_paragraph = {}
summary_lines = []

for para_key, ranked_docs in top_n_results.items():
    selected_docs = []
    
    # ranked_docs sudah berisi 2 skor terbesar per paragraph
    for doc_key, score in ranked_docs.items():
        original_text = doc_text_map.get(doc_key, "")
        if original_text:
            selected_docs.append({
                "doc_key": doc_key,
                "score": score,
                "text": original_text
            })
    
    summary_per_paragraph[para_key] = selected_docs
    
    # Versi ringkas: hanya teks kalimat asli
    for item in selected_docs:
        summary_lines.append(f"{item['text']}")
    summary_lines.append("")  # Baris kosong sebagai pemisah

# Gabungkan semua menjadi summary akhir
final_summary = "\n".join(summary_lines).strip()

print(f"\n=== SUMMARY (Top-{n} per Paragraph) ===\n")
print(final_summary)

# Optional: Simpan summary ke file
output_file = f"summary/summary_{query.replace(' ', '_')}.txt"
with open(output_file, "w", encoding="utf-8") as f:
    f.write(final_summary)
print(f"\n✓ Summary telah disimpan ke '{output_file}'")

=== SUMMARY (Top-3 per Paragraph) ===

Here are four ways that being among nature can help improve your health.
Being outdoors can trigger measurable changes inside your body from lowering stress hormones, easing blood pressure and even improving your gut health.
Spending just 20 minutes in nature can trigger measurable changes inside your body

The evidence for the benefits of spending time in nature is compelling enough that some areas have trialled so called green social prescribing connecting people with nature to improve their phsyical and mental health, with a positive impact on happiness and wellbeing.
A UK study, involving nearly 20,000 people, found that those who spent at least a total of 120 minutes every week in greenery were significantly more likely to report good health and higher psychological well-being.
When you see green trees, smell pine and hear gentle rustling leaves or the sound of birdsong, your autonomic nervous system - a network of nerves controlling unconscious processes - responds instantly.

Willis says that spending time outdoors triggers our endocrine system and lowers levels of cortisol and adrenaline - the hormones that surge when you're stressed or anxious.
"A study found that people in a hotel room for three days who were breathing in Hinoki (Japanese cypress) oil saw a big drop in the adrenaline hormone and a large increase in natural killer cells in their blood."
Natural killer cells are cells that tackle viruses in the body. The participants in the study still had elevated natural killer cells in their body two weeks after inhaling the smell.

Smelling nature is just as powerful as seeing and hearing it.
You may think that the relaxing effect of nature is all in your mind, but another study found that even very young babies with no memory associated with particular smells, still calmed down when another scent associated with calming, limonene was puffed into the room they were in.
The scent of trees and soil is full of organic compounds released by plants and "when you breathe them in, some molecules pass into the bloodstream."

Prof Ming Kuo has studied the effect on factors such as infection susceptibility as well as mental health and says breathing in certain ones have the potential to boost your mood; and the antimicrobial chemicals released by plants – called phytoncides – could help fight disease.
As well as soothing your mind, nature can also help boost your microbiome as soil and plants are full of good bacteria.
Dr Chris van Tulleken says as an infection scientist he sees nature as a positively challenging environment that "tickles your immune system".

Even having a nature screensaver on your laptop can help you relax
Even small touches of nature at home can make a difference, according to Willis.
Research shows that looking at pictures of nature on your laptop or simply gazing out at something green can trigger the same calming brainwave changes and reduce stress.

✓ Summary telah disimpan ke 'summary_Nature_and_outdoors_can_help_boost_your_health_-_here's_how.txt'